name: sentinel-env # The name of your conda environment

channels:
  - conda-forge
  - defaults

dependencies:
  # --- Core Python ---
  - python=3.11

  # --- Your Project's Conda Dependencies ---
    # --- Core Data Science Libraries ---
  - numpy
  - pandas
  - matplotlib

  - pip:
    # Code Quality & Formatting
    - autoflake
    - black       # The uncompromising code formatter
    - black[jupyter]
    - isort       # Sorts imports automatically
    - flake8      # A great linter for catching errors
    - mypy        # For static type checking

    # Testing
    - pytest
    - pytest-cov
    - httpx      

    # Debugging & IDE Integration
    - debugpy   

    # Pre-commit hooks to automate code quality checks
    - pre-commit
