dependencies:
  # --- Application Runtime Dependencies ---
  - fastapi
  - pydantic
  - redis-py 
  - feedparser
  - uvicorn 
  - python-dotenv 
  - requests
  - pysocks

  - beautifulsoup4
  - trafilatura
  - user-agents
  - psutil
  
  # --- Your Project's PIP Dependencies ---
  - pip
  - pip:
    - types-requests
    - types-psutil
    - fake_useragent
    - selenium
    - undetected-chromedriver 
    - selenium-wire
    - blinker==1.7.0
    - pyvirtualdisplay
    - sqlalchemy
