  version: '3.8'

  x-common-env: &common-env
    env_file:
      - ../../.env

  x-prioritiser-service: &prioritiser-service
    image: sentinel/job-prioritiser:latest
    build:
      context: ../../
      dockerfile: ./microservices/job_prioritiser/Dockerfile
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - sentinel-net

  services:
    # --- INFRASTRUCTURE ---
    redis:
      container_name: sentinel-redis-container
      image: "redis:alpine"
      ports:
        - "${REDIS_PORT}:6379"
      volumes:
        - redis_data:/data
      restart: unless-stopped
      networks:
        - sentinel-net

    postgres:
      container_name: sentinel-postgres-container
      image: pgvector/pgvector:pg15
      ports:
        - "${POSTGRES_PORT}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
        # --- INJECT INIT SQL INTO DB
        - ${HOST_ROOT}/microservices/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      # healthcheck:
      #   test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      #   interval: 10s
      #   timeout: 5s
      #   retries: 5
      <<: *common-env
      restart: unless-stopped
      networks:
        - sentinel-net
      command: postgres -c shared_preload_libraries=vector

    # --- MICROSERVICES ---
    api-service:
      container_name: sentinel-api-service-container
      image: sentinel/api-service:latest
      build:
        context: ../../
        dockerfile: ./microservices/api/Dockerfile

      depends_on:
        postgres:
          condition: service_started
        redis:
          condition: service_started

      volumes:
        - ${HOST_LOG_ROOT}/api:/app/logs
        
      ports:
        - "${API_SERVICE_PORT}:8001"

      <<: *common-env
      restart: unless-stopped
      networks:
        - sentinel-net

    # ingestor-service:
    #   container_name: sentinel-ingestor-service-container
    #   image: sentinel/ingestor-service:latest
    #   build: 
    #     context: ../../
    #     dockerfile: ./microservices/ingestor/Dockerfile
    #   depends_on:
    #     - redis

    #   volumes:
    #     - ${HOST_LOG_ROOT}/ingestor:/app/logs

    #   <<: *common-env
    #   restart: unless-stopped
    #   networks:
    #     - sentinel-net

    #   environment:
    #     - REDIS_DUPLICATE_FILTER_KEY=ingestor:seen.articles
    #     - OUTPUT_STREAM=ingestor:to.be.scraped
    #     - MAX_INGESTOR_WORKERS=100

    # scraper-prioritiser:  
    #   <<: [ *common-env, *prioritiser-service ]
    #   container_name: sentinel-scraper-prioritiser-service-container
    #   environment:
    #     - INPUT_STREAMS=ingestor:to.be.scraped, user:to.be.scraped
    #     - OUTPUT_STREAM=prioritised:to.be.scraped
    #     - GROUP_NAME=default
    #     - CONSUMER_NAME=scraper-prioritiser-1
    #     - BATCH_SIZE=100
    #     - MAX_PUBLISH_WORKERS=10

    #   depends_on:
    #     - ingestor-service
    #   volumes:
    #     - ${HOST_LOG_ROOT}/scraper_prioritiser:/app/logs

    # web_scraper-service:
    #   container_name: sentinel-web-scraper-service-container
    #   image: sentinel/web-scraper-service:latest
    #   build: 
    #     context: ../../
    #     dockerfile: ./microservices/web_scraper/Dockerfile
    #   shm_size: '4gb'
    #   ipc: host 
    #   depends_on:
    #     # - postgres
    #     - redis
    #     - ingestor-service
    #     - scraper-prioritiser
      
    #   volumes:
    #     - ${HOST_LOG_ROOT}/scraper/logs:/app/logs
    #     - ${HOST_LOG_ROOT}/scraper/screenshots:/app/screenshots
    #   <<: *common-env 
    #   restart: always
    #   networks:
    #     - sentinel-net

    #   environment:
    #     - INPUT_STREAM=prioritised:to.be.scraped
    #     - USER_OUTPUT_STREAM=user:to.be.nlp
    #     - BACKGROUND_OUTPUT_STREAM=background:to.be.nlp
    #     - FAILURE_OUTPUT_STREAM=failure:to.be.scraped
    #     - BATCH_SIZE=10
    #     - GROUP_NAME=default
    #     - CONSUMER_NAME=web-scraper-1
    #     - SCRAPER_MAX_WORKERS=2
    #     - MAX_PROXY_VALIDATION_WORKERS=100
    #     - MAX_FETCH_RETRIES=3
    #     - INITIAL_FETCH_DELAY_S=1
    #     - FETCH_DELAY_GROWTH_RATE=1.2
      
  volumes:
    redis_data: {}
    postgres_data: {}

  networks:
    sentinel-net:
      driver: bridge
